PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osgeo: <http://data.ordnancesurvey.co.uk/ontology/geometry/>
PREFIX places: <https://pleiades.stoa.org/places/>
PREFIX pleiades: <https://pleiades.stoa.org/places/vocab#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT
{
  ?place
    a pleiades:Place ;
    pleiades:hasFeatureType ?place_type ;
    pleiades:hasRepresentativePoint ?repr_point_geojson ;
    pleiades:hasLocation ?location ;
    dcterms:title ?place_title ;
    dcterms:description ?place_description ;
    .

  ?place_type
    a skos:Concept ;
    skos:prefLabel ?place_type_label ;
    .

  ?location
    a pleiades:Location ;
    dcterms:title ?location_title ;
    osgeo:asGeoJSON ?location_geojson ;
    .
}
WHERE
{
  SERVICE <x-sparql-anything:location=data/pleiades-places-latest.json>
  {
    fx:properties fx:json.literalize "geometry" .

    ?place_node
      xyz:id ?place_id ;
      xyz:uri ?place_uri_as_str ;
      xyz:title ?place_title ;
      xyz:description ?place_description ;
      xyz:placeTypeURIs ?place_type_uris ;
      xyz:locations ?locations ;
      .

    ?place_type_uris fx:anySlot ?place_type_uri_as_str .
    ?locations fx:anySlot ?location_node .

    ?location_node
      xyz:uri ?location_uri_as_str ;
      xyz:title ?location_title ;
      xyz:geometry ?geojson_as_str ;
      .
    BIND(IF(?geojson_as_str != "null", STRDT(?geojson_as_str, geo:geoJSONLiteral), ?unbound) AS ?location_geojson)

    OPTIONAL
    {
      ?place_node xyz:reprPoint ?repr_point .
      ?repr_point rdf:_1 ?repr_point_lng ; rdf:_2 ?repr_point_lat .
      BIND(STRDT(CONCAT(
        '{"type": "Point", "coordinates": [',
        STR(?repr_point_lng),
        ", ",
        STR(?repr_point_lat),
        "]}"), geo:geoJSONLiteral) AS ?repr_point_geojson)
    }

    BIND(IRI(?place_uri_as_str) AS ?place)
    BIND(IRI(?place_type_uri_as_str) as ?place_type)
    BIND(IRI(?location_uri_as_str) as ?location)
  }
  SERVICE <x-sparql-anything:location=data/place-types.ttl>
  {
    ?place_type
      a skos:Concept ;
      skos:prefLabel ?place_type_label ;
      .
  }
}
